name: CI

on:
  push:
    branches: [ "dev","main"]

jobs:

  set_var:
    name: set_var
    runs-on: ubuntu-latest
    steps:
      - name: set dev
        shell: bash
        run: |
          echo "1234567890" > math-homework.txt
          echo "everest-dev" >> math-homework.txt
      
      - name: set main
        shell: bash
        run: |
          echo "0987654321" > math-homework.txt
          echo "everest-main" >> math-homework.txt
          
      - name: Upload math result
        uses: actions/upload-artifact@v3
        with:
          name: homework
          path: math-homework.txt

  display:
    name: Display results
    needs: ["set_var"]
    runs-on: ubuntu-latest
    steps:
      - name: Download math result
        uses: actions/download-artifact@v3
        with:
          name: homework
      - name: Print the final result
        shell: bash
        run: |
          acc_id=`sed -n '1p' math-homework.txt`
          echo The acc_id is $acc_id
          stack_name=`sed -n '2p' math-homework.txt`
          echo The stack_name is $stack_name