name: "actions-demo"

on:
  push:
    branches:
      - dev
      - main

jobs:
    build:
        name: Build Docker Image
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        
        run: |
            echo "DOCKER_IMAGE_NAME=my.docker.repo/awesome-image:release" >> $GITHUB_ENV
        if: startsWith(github.ref, 'refs/tags/dev')
        
        run: |
            echo "DOCKER_IMAGE_NAME=my.docker.repo/awesome-image:staging" >> $GITHUB_ENV
        if: startsWith(github.ref, 'refs/tags/main')

        run: |
            echo "$DOCKER_IMAGE_NAME"