name: GHA Testing
on:
    workflow_dispatch:
        inputs:
            environment:
                description: 'Name of the enviroment to be deployed'
                required: true
                type: environment
                options:
                    - Dev
                    - Qa

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Step 1
              env:
                GREETING: ${{ vars.GREET }}
              run: |
                echo "Environment: ${{ inputs.environment }}"
                echo "${{ env.GREETING }}"
            