name: "actions-demo"

on:
  push:
    branches:
      - dev
      - main

jobs:
    set_env:
        name: set env var in dev
        if: github.ref == 'refs/heads/dev'
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        
        - run: |
            echo "acc_id=1234567890" >> $GITHUB_ENV
        