name: GHA Testing
on:
    workflow_dispatch:
        inputs:
            environment:
                description: 'Name of the enviroment to be deployed'
                required: true
                type: environment
                options:
                    - Dev
                    - Qa
env:
    greet: ${{ secrets.Greet }}
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - run: |
                echo "Environment: $environment"
                echo "$env:greet"
            