name: "actions-demo"

on:
  push:
    branches:
      - dev
      - main

jobs:
    set_env_dev:
        if: github.ref == 'refs/heads/dev'
        name: set_env_dev
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - run: |
            echo "acc_id=1234567890" >> $GITHUB_ENV
        
    set_env_main:
        if: github.ref == 'refs/heads/main'
        name: set_env_main
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: |
                echo "acc_id=0987654321" >> $GITHUB_ENV
    
    display_env:
        if: ${{always() }}
        needs: [set_env_dev,set_env_main]
        name: display_env_var
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: |
                echo $GITHUB_ENV
