name: "actions-demo"

on:
  push:
    branches:
      - dev
      - main

jobs:
    set_env_dev:
        if: github.ref == 'refs/heads/dev'
        name: set_env_dev
        runs-on: ubuntu-latest
        outputs:
            output1: ${{ steps.step1.outputs.test }}
        steps:
            - id: step1
              run: echo "::set-output name=test::dev"   
        
    set_env_main:
        if: github.ref == 'refs/heads/main'
        name: set_env_main
        runs-on: ubuntu-latest
        outputs:
            output1: ${{ steps.step1.outputs.test }}
        steps:
            - id: step1
              run: echo "::set-output name=test::main"   

    
    display_env_var:
        if: ${{always() }}
        needs: [set_env_dev,set_env_main]
        name: display_env_var
        runs-on: ubuntu-latest
        steps:
            - env:
                OUTPUT1: ${{needs.job1.outputs.output1}}
              run: echo "$OUTPUT1"